---@class UI
---@field main MainUI
---@field help HelpUI

---@class MainUI
---@field win integer|nil
---@field buf integer|nil
---@field title string

---@class HelpUI
---@field win integer|nil
---@field buf integer|nil
---@field ns integer|nil
---@field scrollbar_buf integer|nil
---@field scrollbar_win integer|nil
---@field scrollbar_ns integer|nil
---@field bar_pos integer

---@class ColorPicker
---@field adjust_color function
---@field blue number
---@field close function
---@field confirm function
---@field confirm_select function
---@field create_autocmds function
---@field cur_pos table
---@field export function
---@field get_select_opts function
---@field green number
---@field init function
---@field ns_b number
---@field ns_g number
---@field ns_main number
---@field ns_r number
---@field pick function
---@field prev_win integer
---@field red number
---@field replace function
---@field replace_select function
---@field set_color_value function
---@field set_keymaps function
---@field set_picker_lines function
---@field set_to_white_or_black function
---@field update function
---@field update_highlights function
---@field current string

---@class Colors
---@field first_color string
---@field second_color string
---@field gradient table|nil

---@class WinConfig
---@field relative 'editor'|'cursor'
---@field zindex integer
---@field width integer
---@field col integer
---@field row integer
---@field height integer
---@field border any

---@class Blender
---@field idx integer
---@field cur_pos { [1]: integer, [2]: integer }
---@field ns integer
---@field help_ns integer
---@field win_config WinConfig

---@class ColorsMappings
---@field disable? string|string[]
---@field scroll_up? string
---@field scroll_down? string
---@field increment? string
---@field increment_big? string
---@field increment_bigger? string
---@field decrement? string
---@field decrement_big? string
---@field decrement_bigger? string
---@field min_value? string
---@field max_value? string
---@field save_to_register_default? string
---@field save_to_register_choose? string
---@field replace_default? string
---@field replace_choose? string
---@field export? string
---@field set_picker_to_black? string
---@field set_picker_to_white? string

---@class ColorsConfig
---@field register? string
---@field preview? string
---@field default_format? Format
---@field default_insert? boolean
---@field open_help_by_default? boolean
---@field fallback_color? string
---@field border? string
---@field debug? boolean
---@field mappings? ColorsMappings
---@field css ColorsCssConfig

---@class ColorTable
---@field start_pos integer
---@field end_pos integer
---@field match string
---@field rgb_values RGB
---@field type Format

-- css specific configuration
---@class ColorsCssConfig
-- Sets the default list of css colors to choose from
---@field default_css_list? 'mui'|'chakra'|'tailwind'|'base'
-- True uses the css color name by default. False gets associated hex value
---@field use_color_name_by_default? boolean,
-- Telescope config options
---@field use_telescope? boolean
---
---@field telescope_config? ColorsExtConfig

--- Configuration for telescope extension
---
--- **Default configuration**
--- ```lua
--- -- other telescope config settings...
--- extensions = {
---   colors = {
---     telescope_theme = 'dropdown',
---     select_behavior = 'replace',
---     fallback_behavior = 'save',
---     use_names = true,
---     always_save = true
---   }
--- }
--- ```
---
--- @class ColorsExtConfig
---  Sets the behavior of the picker when a color is selected.
---  `replace` - Replaces the color under the cursor
---  `insert` - Inserts the color at the cursor
---  `save` - Saves the color in the default register
---
---  ---
---  __Default:__ `replace`
--- @field select_behavior? 'replace'|'insert'|'save'
---  `True` uses css color names by default. `False` uses hex values.
---
---  ---
---  __Default:__ `True`
--- @field use_names? boolean
---
---  `True` always saves the selected color the default register
---
---  ---
---  __Default:__ `True`
--- @field always_save? boolean
---
--- Defines the behavior in the event of a failure.
--- Typically used with `select_behavior` = "replace".
--- If a color is not found under the cursor,
--- then the plugin will either `save` or `insert` based on this parameter.
---
---  ---
---  __Default:__ `save`
--- @field fallback_behavior? 'insert'|'save'
---
--- Sets the theme for the telescope picker
---
---  ---
---  __Default:__ `dropdown`
--- @field telescope_theme? 'dropdown'|'cursor'|'ivy'

---@alias Format
---|'rgb'
---|'hsl'
---|'hex'

---@alias RGB { [1]: integer, [2]: integer, [3]: integer }
---@alias ColorListItem { [1]: string, [2]: string }
---@alias ColorListName 'base'|'chakra'|'mui'|'tailwind'
